FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --group migrate --no-install-project

COPY . .

CMD ["uv", "run", "--no-dev", "--group", "migrate", "alembic", "upgrade", "head"]
