"""Add fields (min_score and system_promt) to knowledge_bases

Revision ID: 1210209440ba
Revises: 58a2aa08f833
Create Date: 2026-07-03 11:38:34.539881

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1210209440ba'
down_revision: Union[str, Sequence[str], None] = '58a2aa08f833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('min_score', sa.Float(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'system_prompt')
    op.drop_column('knowledge_bases', 'min_score')
    # ### end Alembic commands ###
