"""add_requests_per_minute_to_users

Revision ID: 3007890ac5f6
Revises: a990d31a29da
Create Date: 2026-06-14 20:50:38.254904

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3007890ac5f6'
down_revision: Union[str, Sequence[str], None] = 'a990d31a29da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requests_per_minute', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requests_per_minute')
    # ### end Alembic commands ###
