"""Add embedding models and knowledge bases

Revision ID: 4116f779bda5
Revises: e5d184400dd5
Create Date: 2026-06-30 17:36:11.938182

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4116f779bda5'
down_revision: Union[str, Sequence[str], None] = 'e5d184400dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_models',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('provider_model', sa.String(length=255), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('deleted_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_embedding_models_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_models'))
    )
    op.create_index(op.f('ix_embedding_models_collection_name'), 'embedding_models', ['collection_name'], unique=True)
    op.create_index(op.f('ix_embedding_models_provider_id'), 'embedding_models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_embedding_models_public_id'), 'embedding_models', ['public_id'], unique=True)
    op.create_table('knowledge_bases',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('embedding_model_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('deleted_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], name=op.f('fk_knowledge_bases_embedding_model_id_embedding_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases'))
    )
    op.create_index(op.f('ix_knowledge_bases_embedding_model_id'), 'knowledge_bases', ['embedding_model_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_public_id'), 'knowledge_bases', ['public_id'], unique=True)
    op.add_column('documents', sa.Column('knowledge_base_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False))
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(op.f('fk_documents_knowledge_base_id_knowledge_bases'), 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.alter_column('llm_models', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('llm_models', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('providers', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providers', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('llm_models', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('llm_models', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_documents_knowledge_base_id_knowledge_bases'), 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_column('documents', 'knowledge_base_id')
    op.drop_index(op.f('ix_knowledge_bases_public_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_embedding_model_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_embedding_models_public_id'), table_name='embedding_models')
    op.drop_index(op.f('ix_embedding_models_provider_id'), table_name='embedding_models')
    op.drop_index(op.f('ix_embedding_models_collection_name'), table_name='embedding_models')
    op.drop_table('embedding_models')
    # ### end Alembic commands ###
