"""Add knowledge base tracking to chat_completion_requests

Revision ID: 58a2aa08f833
Revises: 23b010c1c175
Create Date: 2026-07-02 14:39:50.272476

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a2aa08f833'
down_revision: Union[str, Sequence[str], None] = '23b010c1c175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_completion_requests', sa.Column('knowledge_base_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True))
    op.add_column('chat_completion_requests', sa.Column('knowledge_base_public_id', sa.String(length=255), nullable=True))
    # Backfill existing rows to false via a server default, then drop it so the ORM supplies the
    # value on insert going forward.
    op.add_column('chat_completion_requests', sa.Column('used_retrieval', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('chat_completion_requests', 'used_retrieval', server_default=None)
    op.add_column('chat_completion_requests', sa.Column('retrieved_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_chat_completion_requests_knowledge_base_id'), 'chat_completion_requests', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_chat_completion_requests_knowledge_base_public_id'), 'chat_completion_requests', ['knowledge_base_public_id'], unique=False)
    op.create_index(op.f('ix_chat_completion_requests_used_retrieval'), 'chat_completion_requests', ['used_retrieval'], unique=False)
    op.create_foreign_key(op.f('fk_chat_completion_requests_knowledge_base_id_knowledge_bases'), 'chat_completion_requests', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_completion_requests_knowledge_base_id_knowledge_bases'), 'chat_completion_requests', type_='foreignkey')
    op.drop_index(op.f('ix_chat_completion_requests_used_retrieval'), table_name='chat_completion_requests')
    op.drop_index(op.f('ix_chat_completion_requests_knowledge_base_public_id'), table_name='chat_completion_requests')
    op.drop_index(op.f('ix_chat_completion_requests_knowledge_base_id'), table_name='chat_completion_requests')
    op.drop_column('chat_completion_requests', 'retrieved_document_ids')
    op.drop_column('chat_completion_requests', 'used_retrieval')
    op.drop_column('chat_completion_requests', 'knowledge_base_public_id')
    op.drop_column('chat_completion_requests', 'knowledge_base_id')
    # ### end Alembic commands ###
