"""Add ChatCompletionRequestLogModel

Revision ID: a990d31a29da
Revises: 6322d650d1c7
Create Date: 2026-06-01 15:42:06.341355

"""

from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a990d31a29da"
down_revision: Union[str, Sequence[str], None] = "6322d650d1c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_completion_requests",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("api_key_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("user_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("model_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column("model_public_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("provider_model", sa.String(length=255), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("completion_id", sa.String(length=255), nullable=True),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "SUCCEEDED", "FAILED", "INTERRUPTED", name="chatcompletionrequeststatus"
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("chunks_count", sa.Integer(), nullable=True),
        sa.Column("retrieval_total_ms", sa.Float(), nullable=True),
        sa.Column("ollama_embedding_ms", sa.Float(), nullable=True),
        sa.Column("qdrant_search_ms", sa.Float(), nullable=True),
        sa.Column("ollama_ttfb_ms", sa.Float(), nullable=True),
        sa.Column("ollama_generation_ms", sa.Float(), nullable=True),
        sa.Column("total_ms", sa.Float(), nullable=True),
        sa.Column("messages_count", sa.Integer(), nullable=True),
        sa.Column("query_length", sa.Integer(), nullable=True),
        sa.Column(
            "deleted_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name=op.f("fk_chat_completion_requests_api_key_id_api_keys"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_chat_completion_requests_model_id_llm_models"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_chat_completion_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_completion_requests")),
    )
    op.create_index(
        op.f("ix_chat_completion_requests_api_key_id"),
        "chat_completion_requests",
        ["api_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_completion_id"),
        "chat_completion_requests",
        ["completion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_model_id"),
        "chat_completion_requests",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_model_public_id"),
        "chat_completion_requests",
        ["model_public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_request_id"),
        "chat_completion_requests",
        ["request_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_status"),
        "chat_completion_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_completion_requests_user_id"),
        "chat_completion_requests",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_completion_requests_user_id"), table_name="chat_completion_requests"
    )
    op.drop_index(op.f("ix_chat_completion_requests_status"), table_name="chat_completion_requests")
    op.drop_index(
        op.f("ix_chat_completion_requests_request_id"), table_name="chat_completion_requests"
    )
    op.drop_index(
        op.f("ix_chat_completion_requests_model_public_id"), table_name="chat_completion_requests"
    )
    op.drop_index(
        op.f("ix_chat_completion_requests_model_id"), table_name="chat_completion_requests"
    )
    op.drop_index(
        op.f("ix_chat_completion_requests_completion_id"), table_name="chat_completion_requests"
    )
    op.drop_index(
        op.f("ix_chat_completion_requests_api_key_id"), table_name="chat_completion_requests"
    )
    op.drop_table("chat_completion_requests")
    # ### end Alembic commands ###
