"""Add providers and link llm_models

Revision ID: e5d184400dd5
Revises: e807e6f763c0
Create Date: 2026-06-30 14:58:35.625414

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d184400dd5'
down_revision: Union[str, Sequence[str], None] = 'e807e6f763c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=1024), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_public_id'), 'providers', ['public_id'], unique=True)
    op.add_column('llm_models', sa.Column('provider_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True))
    op.create_index(op.f('ix_llm_models_provider_id'), 'llm_models', ['provider_id'], unique=False)
    op.create_foreign_key(op.f('fk_llm_models_provider_id_providers'), 'llm_models', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_llm_models_provider_id_providers'), 'llm_models', type_='foreignkey')
    op.drop_index(op.f('ix_llm_models_provider_id'), table_name='llm_models')
    op.drop_column('llm_models', 'provider_id')
    op.drop_index(op.f('ix_providers_public_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
