"""rename_ollama_metrics_to_provider_agnostic

Revision ID: e807e6f763c0
Revises: 3007890ac5f6
Create Date: 2026-06-18 17:16:03.106351

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e807e6f763c0'
down_revision: Union[str, Sequence[str], None] = '3007890ac5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_completion_requests', sa.Column('embedding_ms', sa.Float(), nullable=True))
    op.add_column('chat_completion_requests', sa.Column('llm_ttfb_ms', sa.Float(), nullable=True))
    op.add_column('chat_completion_requests', sa.Column('llm_generation_ms', sa.Float(), nullable=True))
    op.drop_column('chat_completion_requests', 'ollama_generation_ms')
    op.drop_column('chat_completion_requests', 'ollama_embedding_ms')
    op.drop_column('chat_completion_requests', 'ollama_ttfb_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_completion_requests', sa.Column('ollama_ttfb_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('chat_completion_requests', sa.Column('ollama_embedding_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('chat_completion_requests', sa.Column('ollama_generation_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('chat_completion_requests', 'llm_generation_ms')
    op.drop_column('chat_completion_requests', 'llm_ttfb_ms')
    op.drop_column('chat_completion_requests', 'embedding_ms')
    # ### end Alembic commands ###
